<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/admin_notifications/localization/<lang>.inc                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail admin_notifications plugin |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['notifications'] = 'Notifications';
$labels['notifications_create'] = 'New notification';
$labels['notification_title'] = 'Title';
$labels['notification_message'] = 'Message';
$labels['notification_isactive'] = 'Is it active?';
$labels['notification_active'] = 'Active';
$labels['notification_disabled'] = 'Disabled';
$labels['notification_add'] = 'Save notification';
$labels['notification_delete'] = 'Are you sure you want to delete this notification?';

?>
