<?php

/*
 +-----------------------------------------------------------------------+
 | plugins/admin_notifications/localization/<lang>.inc                   |
 |                                                                       |
 | Localization file of the Roundcube Webmail admin_notifications plugin |
 |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 |                                                                       |
 +-----------------------------------------------------------------------+

*/

$labels = array();
$labels['notifications'] = 'Notificationes';
$labels['notifications_create'] = 'Nueva notificación';
$labels['notification_title'] = 'Titulo';
$labels['notification_message'] = 'Mensaje';
$labels['notification_isactive'] = 'Está activa?';
$labels['notification_active'] = 'Activo';
$labels['notification_disabled'] = 'Desabilitado';
$labels['notification_add'] = 'Guardar notificación';
$labels['notification_delete'] = '¿Está seguro que desea eliminar esta notificación?';

?>
